using UnityEngine;

namespace ArknightsACT.Gameplay.Presentation
{
    /// <summary>
    /// Exposes a presentation-only lock to systems that must not cover an active combat effect
    /// with a full-screen UI. This is intentionally separate from gameplay skill state: damage
    /// and movement may finish before the authored effect has visually completed.
    /// </summary>
    public interface IGameplayPresentationLock
    {
        bool IsPresentationBusy { get; }
    }

    /// <summary>
    /// Runtime metadata and playback helper for a frame-sequence FX prefab generated by the
    /// extracted-effect importer. The importer owns the Animator/clip; this component only
    /// provides a stable lifetime contract to gameplay-specific FX controllers.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class ExtractedFrameFxPlayback : MonoBehaviour
    {
        public const float DefaultPlaybackSpeed = 1f;
        public const float BasicAttackPlaybackSpeed = 2f;

        [SerializeField] private Animator animator;
        [SerializeField, Min(0.01f)] private float duration = 1f;
        [SerializeField] private bool loop;
        [SerializeField, Min(0.01f)] private float playbackSpeed = DefaultPlaybackSpeed;

        public float Duration => Mathf.Max(0.01f, duration);
        public float EffectiveDuration => Duration / PlaybackSpeed;
        public float PlaybackSpeed => playbackSpeed > 0f
            ? Mathf.Max(0.01f, playbackSpeed)
            : DefaultPlaybackSpeed;
        public bool Loop => loop;

        public void Configure(
            Animator animatorValue,
            float durationValue,
            bool loopValue,
            float playbackSpeedValue = DefaultPlaybackSpeed)
        {
            animator = animatorValue;
            duration = Mathf.Max(0.01f, durationValue);
            loop = loopValue;
            playbackSpeed = Mathf.Max(0.01f, playbackSpeedValue);
            ApplyPlaybackSpeed();
        }

        public void SetPlaybackSpeed(float value)
        {
            playbackSpeed = Mathf.Max(0.01f, value);
            ApplyPlaybackSpeed();
        }

        public void PlayFromStart()
        {
            if (animator == null)
                animator = GetComponent<Animator>();
            if (animator == null)
                return;

            animator.enabled = true;
            ApplyPlaybackSpeed();
            animator.Rebind();
            animator.Update(0f);
            animator.Play(0, 0, 0f);
        }

        public void Stop()
        {
            if (animator != null)
                animator.enabled = false;
        }

        private void Awake() => ApplyPlaybackSpeed();

        private void OnEnable() => ApplyPlaybackSpeed();

        private void ApplyPlaybackSpeed()
        {
            if (animator != null)
                animator.speed = PlaybackSpeed;
        }
    }
}
