using System;
using System.Collections.Generic;
using ArknightsACT.Gameplay.Roguelite.Routing;
using UnityEngine;

namespace ArknightsACT.Gameplay.Roguelite.World
{
    /// <summary>
    /// Replaces the selected Concept-01 runtime blockout skin with persistent reusable environment
    /// modules generated by the Editor kit builder. Gameplay colliders, pit logic, navigation and
    /// encounter placement stay untouched.
    /// </summary>
    [DefaultExecutionOrder(15)]
    [DisallowMultipleComponent]
    public sealed class RogueliteStageModularKitController : MonoBehaviour
    {
        private const float ChunkWidth = 14f;
        private const float ChunkDepth = 11f;
        private const float WallModuleWidth = 2.4f;

        [SerializeField] private RogueliteStageMapController stageMap;
        [SerializeField] private ChernobogEnvironmentKit kit;

        private readonly HashSet<int> _skinnedPits = new();
        private GameObject _preparedStage;
        private float _nextResolveAt;

        public void Configure(RogueliteStageMapController map, ChernobogEnvironmentKit environmentKit)
        {
            stageMap = map;
            kit = environmentKit;
        }

        private void Update()
        {
            if (Time.unscaledTime < _nextResolveAt)
                return;
            _nextResolveAt = Time.unscaledTime + 0.12f;

            stageMap ??= FindFirstObjectByType<RogueliteStageMapController>();
            if (stageMap == null || kit == null || !kit.IsUsable)
                return;

            var stage = GameObject.Find($"[Stage_{stageMap.StageIndex:00}_Runtime]");
            if (stage == null)
                return;

            if (stage != _preparedStage)
            {
                _skinnedPits.Clear();
                BuildStageKit(stage.transform);
                _preparedStage = stage;
                Debug.Log(
                    $"[ArknightsACT/ModularKit] Stage {stageMap.StageIndex}: persistent Chernobog modules applied.",
                    this);
            }

            SkinNewPits(stage.transform);
        }

        private void BuildStageKit(Transform stage)
        {
            var existing = stage.Find("[Chernobog_ModularKit]");
            if (existing != null)
                Destroy(existing.gameObject);

            DisableConceptBlockoutParts(stage);

            var root = new GameObject("[Chernobog_ModularKit]").transform;
            root.SetParent(stage, false);

            ApplyFloorModules(stage, root);
            ApplyCoverModules(stage, root);
            BuildPerimeter(stage, root);
            DressFacility(stage, root);
            BuildInfrastructure(root);
        }

        private static void DisableConceptBlockoutParts(Transform stage)
        {
            var concept = stage.Find("[Concept01_ChernobogDeckKit]");
            if (concept == null)
                return;

            DisableChild(concept, "Deck");
            DisableChild(concept, "UtilityCover");
            DisableChild(concept, "Perimeter");
        }

        private void ApplyFloorModules(Transform stage, Transform root)
        {
            var detailRoot = new GameObject("FloorDetails").transform;
            detailRoot.SetParent(root, false);

            for (var blockIndex = 0; blockIndex < stageMap.Blocks.Count; blockIndex++)
            {
                var block = FindBlockTransform(stage, blockIndex);
                var sockets = block != null ? block.Find("[FloorSockets]") : null;
                if (block == null || sockets == null)
                    continue;

                var surfaces = sockets.GetComponentsInChildren<Transform>(true);
                var serial = 0;
                for (var i = 0; i < surfaces.Length; i++)
                {
                    var surface = surfaces[i];
                    if (surface == null || !surface.name.StartsWith("FloorSurface_", StringComparison.Ordinal))
                        continue;

                    var filter = surface.GetComponent<MeshFilter>();
                    var renderer = surface.GetComponent<Renderer>();
                    var selector = PositiveMod(stageMap.StageIndex * 43 + blockIndex * 17 + serial * 11, 13);
                    if (filter != null)
                        filter.sharedMesh = selector <= 2 && kit.floorPlateHeavyMesh != null
                            ? kit.floorPlateHeavyMesh
                            : kit.floorPlateMesh;
                    surface.localScale = Vector3.one;
                    if (renderer != null)
                        renderer.sharedMaterial = selector <= 2 && kit.deckHeavyMaterial != null
                            ? kit.deckHeavyMaterial
                            : kit.deckMaterial;

                    // Details are deliberately rare. Most of the board stays visually quiet.
                    var detail = PositiveMod(stageMap.StageIndex * 71 + blockIndex * 31 + serial * 19, 29);
                    if (detail == 0 && kit.floorGrate != null)
                        SpawnFloorDetail(detailRoot, kit.floorGrate, surface.position, block.rotation, "MaintenanceGrate");
                    else if (detail == 13 && kit.floorServiceHatch != null)
                        SpawnFloorDetail(detailRoot, kit.floorServiceHatch, surface.position, block.rotation, "ServiceHatch");

                    serial++;
                }
            }
        }

        private static void SpawnFloorDetail(Transform parent, GameObject prefab, Vector3 worldPosition, Quaternion blockRotation, string name)
        {
            var instance = Instantiate(prefab, parent);
            instance.name = name;
            instance.transform.position = worldPosition + Vector3.up * 0.035f;
            instance.transform.rotation = blockRotation;
        }

        private void ApplyCoverModules(Transform stage, Transform root)
        {
            var coverRoot = new GameObject("GameplayCover").transform;
            coverRoot.SetParent(root, false);

            var transforms = stage.GetComponentsInChildren<Transform>(true);
            var serial = 0;
            for (var i = 0; i < transforms.Length; i++)
            {
                var cover = transforms[i];
                if (cover == null || !string.Equals(cover.name, "GridCover", StringComparison.Ordinal))
                    continue;
                if (cover.Find("[ModularCover]") != null)
                    continue;

                var body = cover.Find("Body");
                if (body == null)
                    continue;

                var bodyRenderer = body.GetComponent<Renderer>();
                if (bodyRenderer != null)
                    bodyRenderer.enabled = false;
                DisableChild(cover, "[Concept01Cover]");

                var size = body.localScale;
                var width = Mathf.Abs(size.x);
                var height = Mathf.Abs(size.y);
                var depth = Mathf.Abs(size.z);
                var selected = SelectCoverPrefab(width, serial);
                if (selected == null)
                    continue;

                var visual = Instantiate(selected, cover);
                visual.name = "[ModularCover]";
                visual.transform.localPosition = Vector3.zero;
                visual.transform.localRotation = Quaternion.identity;

                var canonical = ResolveCanonicalCoverSize(selected);
                visual.transform.localScale = new Vector3(
                    canonical.x > 0.01f ? width / canonical.x : 1f,
                    canonical.y > 0.01f ? height / canonical.y : 1f,
                    canonical.z > 0.01f ? depth / canonical.z : 1f);
                serial++;
            }
        }

        private GameObject SelectCoverPrefab(float width, int serial)
        {
            if (serial % 5 == 4 && kit.electricalCabinet != null && width < 1.7f)
                return kit.electricalCabinet;
            if (width >= 2.15f && kit.hvacLarge != null)
                return kit.hvacLarge;
            if (width >= 1.45f && kit.hvacMedium != null)
                return kit.hvacMedium;
            return kit.hvacSmall;
        }

        private Vector3 ResolveCanonicalCoverSize(GameObject prefab)
        {
            if (prefab == kit.hvacLarge) return new Vector3(2.6f, 0.76f, 0.90f);
            if (prefab == kit.hvacMedium) return new Vector3(1.8f, 0.70f, 0.82f);
            if (prefab == kit.electricalCabinet) return new Vector3(0.82f, 1.15f, 0.62f);
            return new Vector3(1.2f, 0.66f, 0.74f);
        }

        private void BuildPerimeter(Transform stage, Transform root)
        {
            var perimeter = new GameObject("Perimeter").transform;
            perimeter.SetParent(root, false);

            var totalWidth = stageMap.Width * ChunkWidth;
            var totalDepth = stageMap.Height * ChunkDepth;
            BuildWallRun(perimeter, "North", new Vector3(0f, 0f, totalDepth * 0.5f), totalWidth + 0.30f, Vector3.back, kit.wallVent);
            BuildWallRun(perimeter, "East", new Vector3(totalWidth * 0.5f, 0f, 0f), totalDepth, Vector3.left, kit.wallVent);
            BuildWallRun(perimeter, "South", new Vector3(0f, 0f, -totalDepth * 0.5f), totalWidth + 0.30f, Vector3.forward, kit.wallLow != null ? kit.wallLow : kit.wallSolid);
            BuildWallRun(perimeter, "West", new Vector3(-totalWidth * 0.5f, 0f, 0f), totalDepth, Vector3.right, kit.wallLow != null ? kit.wallLow : kit.wallSolid);

            if (kit.wallCorner != null)
            {
                SpawnModule(perimeter, kit.wallCorner, new Vector3(-totalWidth * 0.5f, 0f, -totalDepth * 0.5f), Quaternion.identity, "Corner_SW");
                SpawnModule(perimeter, kit.wallCorner, new Vector3(totalWidth * 0.5f, 0f, -totalDepth * 0.5f), Quaternion.identity, "Corner_SE");
                SpawnModule(perimeter, kit.wallCorner, new Vector3(-totalWidth * 0.5f, 0f, totalDepth * 0.5f), Quaternion.identity, "Corner_NW");
                SpawnModule(perimeter, kit.wallCorner, new Vector3(totalWidth * 0.5f, 0f, totalDepth * 0.5f), Quaternion.identity, "Corner_NE");
            }
        }

        private static void BuildWallRun(Transform parent, string name, Vector3 center, float length, Vector3 inward, GameObject prefab)
        {
            if (prefab == null)
                return;

            var run = new GameObject(name).transform;
            run.SetParent(parent, false);
            run.localPosition = center;
            run.localRotation = Quaternion.LookRotation(inward, Vector3.up);

            var count = Mathf.Max(1, Mathf.CeilToInt(length / WallModuleWidth));
            var span = length / count;
            for (var i = 0; i < count; i++)
            {
                var instance = Instantiate(prefab, run);
                instance.name = $"{name}_Module_{i:00}";
                instance.transform.localPosition = new Vector3(-length * 0.5f + span * (i + 0.5f), 0f, 0f);
                instance.transform.localRotation = Quaternion.identity;
                instance.transform.localScale = new Vector3(span / WallModuleWidth, 1f, 1f);
            }
        }

        private void DressFacility(Transform stage, Transform root)
        {
            var facilityDress = new GameObject("FacilityDress").transform;
            facilityDress.SetParent(root, false);

            var transforms = stage.GetComponentsInChildren<Transform>(true);
            for (var i = 0; i < transforms.Length; i++)
            {
                var facility = transforms[i];
                if (facility == null || !string.Equals(facility.name, "TwoFloorFacility", StringComparison.Ordinal))
                    continue;

                if (kit.hvacMedium != null)
                {
                    var hvac = Instantiate(kit.hvacMedium, facilityDress);
                    hvac.name = "Facility_HVAC";
                    hvac.transform.position = facility.TransformPoint(new Vector3(3.45f, 2.08f, 2.15f));
                    hvac.transform.rotation = facility.rotation;
                }

                if (kit.electricalCabinet != null)
                {
                    var cabinet = Instantiate(kit.electricalCabinet, facilityDress);
                    cabinet.name = "Facility_Electrical";
                    cabinet.transform.position = facility.TransformPoint(new Vector3(4.52f, 0f, 3.72f));
                    cabinet.transform.rotation = facility.rotation * Quaternion.Euler(0f, 180f, 0f);
                }

                if (kit.pipeRun != null)
                {
                    var pipe = Instantiate(kit.pipeRun, facilityDress);
                    pipe.name = "Facility_PipeRun";
                    pipe.transform.position = facility.TransformPoint(new Vector3(4.78f, 0.72f, 3.88f));
                    pipe.transform.rotation = facility.rotation * Quaternion.Euler(0f, 90f, 90f);
                }
            }
        }

        private void BuildInfrastructure(Transform root)
        {
            var infrastructure = new GameObject("Infrastructure").transform;
            infrastructure.SetParent(root, false);

            var width = stageMap.Width * ChunkWidth;
            var depth = stageMap.Height * ChunkDepth;

            if (kit.catwalk != null)
            {
                SpawnModule(infrastructure, kit.catwalk,
                    new Vector3(-width * 0.16f, 2.3f, depth * 0.5f + 2.65f),
                    Quaternion.identity, "North_Catwalk");
                SpawnModule(infrastructure, kit.catwalk,
                    new Vector3(width * 0.5f + 2.55f, 3.15f, depth * 0.18f),
                    Quaternion.Euler(0f, 90f, 0f), "East_Catwalk");
            }

            if (kit.pipeRun != null)
            {
                for (var i = -1; i <= 1; i++)
                {
                    SpawnModule(infrastructure, kit.pipeRun,
                        new Vector3(i * 3.15f, 1.05f, depth * 0.5f + 1.55f),
                        Quaternion.Euler(0f, 90f, 0f), $"North_Pipe_{i + 1}");
                }
            }
        }

        private void SkinNewPits(Transform stage)
        {
            if (kit.pitFrame == null)
                return;

            var transforms = stage.GetComponentsInChildren<Transform>(true);
            for (var i = 0; i < transforms.Length; i++)
            {
                var pit = transforms[i];
                if (pit == null || !pit.name.StartsWith("Hazard_Hole", StringComparison.Ordinal))
                    continue;

                var id = pit.gameObject.GetInstanceID();
                if (_skinnedPits.Contains(id) || pit.Find("[ModularPitFrame]") != null)
                    continue;

                HideRenderer(pit.Find("PitEdgeN"));
                HideRenderer(pit.Find("PitEdgeS"));
                HideRenderer(pit.Find("PitEdgeE"));
                HideRenderer(pit.Find("PitEdgeW"));

                var frame = Instantiate(kit.pitFrame, pit);
                frame.name = "[ModularPitFrame]";
                frame.transform.localPosition = new Vector3(0f, 0.055f, 0f);
                frame.transform.localRotation = Quaternion.identity;
                _skinnedPits.Add(id);
            }
        }

        private static GameObject SpawnModule(Transform parent, GameObject prefab, Vector3 localPosition, Quaternion localRotation, string name)
        {
            var instance = Instantiate(prefab, parent);
            instance.name = name;
            instance.transform.localPosition = localPosition;
            instance.transform.localRotation = localRotation;
            return instance;
        }

        private static void DisableChild(Transform parent, string name)
        {
            if (parent == null)
                return;
            var child = parent.Find(name);
            if (child != null)
                child.gameObject.SetActive(false);
        }

        private static void HideRenderer(Transform target)
        {
            if (target == null)
                return;
            var renderer = target.GetComponent<Renderer>();
            if (renderer != null)
                renderer.enabled = false;
        }

        private static Transform FindBlockTransform(Transform stage, int index)
        {
            var prefix = $"Block_{index:00}_";
            for (var i = 0; i < stage.childCount; i++)
            {
                var child = stage.GetChild(i);
                if (child != null && child.name.StartsWith(prefix, StringComparison.Ordinal))
                    return child;
            }
            return null;
        }

        private static int PositiveMod(int value, int divisor)
        {
            var result = value % divisor;
            return result < 0 ? result + divisor : result;
        }
    }
}
